### ISSUE TITLE
How can I restrict the search to a specific country?

### ISSUE THREAD

**Issue by flyingcoder** [SachinAgarwal1337/google-places-api#10]
I want to have a city search for germany only but when I search for berlin the first result in autocomplete is berlin in new york. 

I can set it directly in the link in google places api.

**Comment by b8ne** [comment]
Hi @flyingcoder did you get this working? I just installed this package and have traced the call stack through and found that any queries are being lost in the GuzzleHTTP.
What format do the params need to be in?

**Comment by iaMeteor** [comment]
@flyingcoder sam question here

**Comment by flyingcoder** [comment]
@b8ne and @iaMeteor. Yes sorry for not updating but the trick is putting regions. ` $params = [
            'region' => 'DE'
        ];` in my case cause I wanted to search for Germany only.
