### ISSUE TITLE
throws error when no results found

### ISSUE THREAD

**Issue by wheredidgogogo** [SachinAgarwal1337/google-places-api#11]
How can the error be handed when no results are found?

For example - if address = 'sdfgdsgdthrtehdrsgstgsdgs##$$#dfg'

$response = $googlePlaces->placeAutocomplete($request->input('address'),['types'=>'geocode']);

Thanks!

**Comment by SachinAgarwal1337** [comment]
@wheredidgogogo `$response` will have the response send from google. So if no results are found google will send `Status = ZERO_RESULT` with appropriate `error_message`. 

you can refer this doc `https://developers.google.com/places/web-service/autocomplete`

**Comment by wheredidgogogo** [comment]
Thanks Sachin

Got it to work :)
