### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by webmarts** [SachinAgarwal1337/google-places-api#16]
Hi

I am willing to use this in one my Codeigniter application,
Can you please share a sample in php which will do a text search 
public function textSearch($query, $params = [])

I tried to use code but giving me error Parse error: syntax error, unexpected '$response'

**Comment by SachinAgarwal1337** [comment]
Hi @webmarts 

I have mentioned it in documentation. But if you are still getting error please provide me with your code snippet and snapshot of error screen so I can help you.
