### ISSUE TITLE
Error when using next_page_token

### ISSUE THREAD

**Issue by 1quintana** [SachinAgarwal1337/google-places-api#17]
If you want to use next_page token, so the next function should be modified, notice that I only added a condition.

and you should send the next param
'pagetoken' => 'all the code for the next page should be here'

public function nearbySearch($location, $radius = null, $params = [])
    {
        $this->checkKey();

        if (!array_key_exists('pagetoken', $params)){
            $params = $this->prepareNearbySearchParams($location, $radius, $params);
        }

        $response = $this->makeRequest(self::NEARBY_SEARCH_URL, $params);

        return $this->convertToCollection($response, 'results');
    }

**Comment by SachinAgarwal1337** [comment]
@1quintana Google do not give error if there are other parameters with `pagetoken`. Google will simply ignore other parameters. 

I tested this, it is not giving any error. But if u are getting error please provide me the code snippet and screen shot of error so I can help u further.
