### ISSUE TITLE
Guzzlehttp/PSR-7 fails combined with slim 3 framework

### ISSUE THREAD

**Issue by itay9001** [SachinAgarwal1337/google-places-api#26]
Hi, When trying to use the following module, I come across the following error coming from Slim 3:

> {
	"code": 0,
	"message": "Middleware must return instance of \\Psr\\Http\\Message\\ResponseInterface",
	"file": "C:\\wamp64\\www\\test\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php",
	"line": 75,
	"trace": [
		"#0 C:\\wamp64\\www\\ff-api-php\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(122): Slim\\Route->Slim\\{closure}(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
		"#1 C:\\wamp64\\www\\ff-api-php\\vendor\\slim\\slim\\Slim\\Route.php(316): Slim\\Route->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
		"#2 C:\\wamp64\\www\\ff-api-php\\vendor\\slim\\slim\\Slim\\App.php(476): Slim\\Route->run(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
		"#3 C:\\wamp64\\www\\ff-api-php\\vendor\\slim\\slim\\Slim\\MiddlewareAwareTrait.php(122): Slim\\App->__invoke(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
		"#4 C:\\wamp64\\www\\ff-api-php\\vendor\\slim\\slim\\Slim\\App.php(370): Slim\\App->callMiddlewareStack(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
		"#5 C:\\wamp64\\www\\ff-api-php\\vendor\\slim\\slim\\Slim\\App.php(295): Slim\\App->process(Object(Slim\\Http\\Request), Object(Slim\\Http\\Response))",
		"#6 C:\\wamp64\\www\\ff-api-php\\app\\server.php(34): Slim\\App->run()",
		"#7 C:\\wamp64\\www\\ff-api-php\\public\\index.php(7): require('C:\\\\wamp64\\\\www\\\\v...')",
		"#8 {main}"
	]
}

It seem that something with the guzzle Http PSR-7 makes the slim to having problems,
Any idea?

**Comment by SachinAgarwal1337** [comment]
@itay9001 This seems to be a slim framework problem. Sorry but there is nothing much I can do. You can probably try slim forums to ask about this.
