### ISSUE TITLE
Laravel collection

### ISSUE THREAD

**Issue by tmaly1980** [SachinAgarwal1337/google-places-api#27]
The docs aren't completely clear about how to use laravel collections with results... I've had to find out the hard way that the results list is buried in $response->get('results') . For placeDetails, it's $response->get('result') .

From there, $response->get('results')->each(), or any other list/loop method in Collection works. 

It would be helpful to update the docs to be more detailed.

**Comment by SachinAgarwal1337** [comment]
@tmaly1980 The Idea is to return the exact result which google apis returns as result in form of Collection. Thus no Docs were given for it. But now that u mentioned it, I think it's better to enhance the result and add docs. Will do it in next release.
