### ISSUE TITLE
More specific exceptions would be great!

### ISSUE THREAD

**Issue by Senci** [SachinAgarwal1337/google-places-api#28]
As far as I can tell, currently there is only the GooglePlacesApiException. To decide what exactly went wrong one currently has to parse the Exception message. In my opinion there should be more specific Exceptions so that one is able to catch and handle them separately. Even faulty responses should get separate Exceptions by response status (i.e.: GooglePlacesApiRequestDeniedException, GooglePlacesApiInvalidRequestException, ...).

**Comment by SachinAgarwal1337** [comment]
@Senci In the latest release, I added Error Message also in the exception. Now you dont need to parse exception message manually.
