### ISSUE TITLE
handling ZERO_RESULTS error in textSearch

### ISSUE THREAD

**Issue by arkhub** [SachinAgarwal1337/google-places-api#29]
When searching using textSearch for text that didn't show any result in google :

```Fatal error: Uncaught SKAgarwal\GoogleApi\Exceptions\GooglePlacesApiException: Response returned with status: ZERO_RESULTS in /var/www/html/testing/vendor/skagarwal/google-places-api/src/PlacesApi.php:217 Stack trace: #0 /var/www/html/testing/vendor/skagarwal/google-places-api/src/PlacesApi.php(86): SKAgarwal\GoogleApi\PlacesApi->makeRequest('textsearch/json', Array) #1 /var/www/html/testing/search.php(8): SKAgarwal\GoogleApi\PlacesApi->textSearch('MY SEARCH QUERY...') #2 {main} thrown in /var/www/html/testing/vendor/skagarwal/google-places-api/src/PlacesApi.php on line 217```

is there any way to handle the zeo result so it wont get fatal error?

**Comment by SachinAgarwal1337** [comment]
@arkhub This has been fixed in new release. You won't get exception for `ZERO_RESULT`
