### ISSUE TITLE
Mistakes / typos in readme

### ISSUE THREAD

**Issue by vovanmix** [SachinAgarwal1337/google-places-api#3]
Please fix some mistakes in readme:
```
composer require skagarwal/google-places-api
```
typo in requrire
```
php artisan vendor:publish --provider="SKAgarwal\GoogleApi\ServiceProvider"
```
quotes required

**Comment by SachinAgarwal1337** [comment]
Sorry for late, I dint see this issue earlier. And yes fixed it. And quotes are not mandatory. :smiley:

**Comment by codru** [comment]
Hello, 

I just want to write you about quotes:
`
vagrant@homestead:~/Code/demo.app$ php artisan vendor:publish --provider=S
KAgarwal/GoogleApi/ServiceProvider
Nothing to publish for tag [].

vagrant@homestead:~/Code/demo.app$ php artisan vendor:publish --provider="
SKAgarwal\GoogleApi\ServiceProvider"
Copied File [/vendor/skagarwal/google-places-api/config/google.php] To [/config/google.php]
Publishing complete for tag []!
`
Thank you :)

**Comment by SachinAgarwal1337** [comment]
@codru Thank you for information. Fixed it. :)
