### ISSUE TITLE
Example of parameters being passed to methods?

### ISSUE THREAD

**Issue by towhitch** [SachinAgarwal1337/google-places-api#31]
Hi, I installed this package and think it's great but I am having a problem providing the parameters to the placeAutocomplete method? I tried several different ways to pass the correct information but without any luck. I was hoping there was an example somewhere I missed with a more in depth example or could one be provided? Thanks for the help.

**Comment by SachinAgarwal1337** [comment]
@towhitch 
# Place Autocomplete
### placeAutocomplete($input, $params = [])
* `input` — The text string on which to search. The Place Autocomplete service will return candidate matches based on this string and order results based on their perceived relevance.
* `params` - **Optional Parameters** You can refer all the available optional parameters on the [Google's Official Webpage](https://developers.google.com/places/web-service/autocomplete)
