### ISSUE TITLE
Curl SSL certificate

### ISSUE THREAD

**Issue by marcus-at-localhorst** [SachinAgarwal1337/google-places-api#36]
Is it possible to temporarily set the `'verify' => false` option in the Guzzle client before or while I call the google-places-api? (I need this on my dev machine)

Right now I changed PlacesApi.php:

```php
$this->client = new Client([
  'base_uri' => 'https://maps.googleapis.com/maps/api/place/',
  'verify' => false
]);
```
But of course I don't want to touch those files.

Maybe an optional second param for guzzle client options is a way? 
```php
$p = new SKAgarwal\GoogleApi\PlacesApi('KEY', []);
```

Thanks!

**Comment by SachinAgarwal1337** [comment]
@marcus-at-localhorst Unless you u use https with invalid ssl certificate on ur dev machine this should not be a prob.

**Comment by SachinAgarwal1337** [comment]
@marcus-at-localhorst https://github.com/SachinAgarwal1337/google-places-api/commit/c7d477d4b6cab2621d6401cdb4f540b5505706c2 Check this. Added a new method `verifySSL()` use this to disable the SSL Verification.

**Comment by marcus-at-localhorst** [comment]
Thank you so much! All the best for 2018!
