### ISSUE TITLE
API KEY is not specified.

### ISSUE THREAD

**Issue by solokkhz** [SachinAgarwal1337/google-places-api#37]
Hi there,

I was following the documentation for installing the places api on laravel 5.5 and i keep getting the "API KEY is not specified." error. I already added the api key in the google.php file, but still getting the same error.

Any idea of what i did wrong during install? 
![whoops there was an error](https://user-images.githubusercontent.com/34383329/36716709-fa637d6c-1ba3-11e8-877e-dffb4109812b.png)

for the test i am trying to run this code in my show.blade.php
{{ GooglePlaces::placeAutocomplete('Jerusalem') }}

**Comment by MarkCorneth** [comment]
How was this closed without solution to the issue? I have the same problem. Could you maybe explain how you resolved this issue
