### ISSUE TITLE
Params example

### ISSUE THREAD

**Issue by yourphnompenh** [SachinAgarwal1337/google-places-api#39]
Hi, can anyone give an example how to use params? I tried it but the results does not reflect it:
$response = $googlePlaces->nearbySearch('11.585125,104.863643', 500,array('type=restaurant'));

**Comment by Yoni116** [comment]
you forgot the > inside the array
it should be:
$googlePlaces->nearbySearch('11.585125,104.863643', 500,array('type=**>**restaurant'));
