### ISSUE TITLE
PHP inbuilt server: GuzzleHttp \ Exception \ RequestException cURL error 60: SSL certificate problem

### ISSUE THREAD

**Issue by abiodunjames** [SachinAgarwal1337/google-places-api#40]
You get SSL certificate error  even when you set `$verifySSL = false` at the constructor. 
This is because it was never set, so it always defaults to true as shown in this snippet irrespective of what you set it to be
```php
/**
     * PlacesApi constructor.
     *
     * @param null $key
     * @param bool $verifySSL
     */
    public function __construct($key = null, $verifySSL = true)
    {
        $this->key = $key;

        $this->client = new Client([
            'base_uri' => self::BASE_URL,
        ]);
    }
```

I'll be making a pull request to address this.

**Comment by SachinAgarwal1337** [comment]
fixed: https://github.com/SachinAgarwal1337/google-places-api/commit/d084ff7c246987bd9fc2dee909b4fb54d58ff6c5
