### ISSUE TITLE
Distance between cities

### ISSUE THREAD

**Issue by maganius** [SachinAgarwal1337/google-places-api#44]
How title says, is possible determine the km between 2 cities?

for example:
Point A: Montevideo, Uruguay
Point B: New York, USA

Distance between A to B: 300km

it's possible?

UPDATE: I think its possible with google geocoder, its implemented on this api?
Check this package: https://github.com/malhal/Laravel-Geographical
it would be awesome if you implements same in your package.

**Comment by SachinAgarwal1337** [comment]
@maganius That package is not using any 3rd Party APIs and calculating using formulas in sql query. So to respect the Author, it will be great if you can use that package. 

P.S I will be adding other google apis soon like Directions API, Distance Matrix API, Geolocation API and others.
