### ISSUE TITLE
Referer header security

### ISSUE THREAD

**Issue by mtx-z** [SachinAgarwal1337/google-places-api#48]
Hello,

I'm coming into an issue with my production key: `Response returned with status: REQUEST_DENIED`.
From what I see, it could come from the referer security. 

I've checked the package method, `vendor/skagarwal/google-places-api/src/PlacesApi.php::makeRequest()`, and it uses a `Guzzle Client` to do the request to Google. 

From [Guzzle documentation](http://docs.guzzlephp.org/en/stable/request-options.html#headers), we can passes headers like this:
```
$client->request('GET', '/get', [
    'headers' => [
        'X-Foo'      => ['Bar', 'Baz']
    ]
]); 
```

We can pass a 2nd parameter to the `$placeApi->placeAutocomplete()` method, but this parameter is passed trought the `vendor/skagarwal/google-places-api/src/PlacesApi.php::getOptions()` method. 

Reading the `getOptions()` code, my solution to pass a `['headers' => ['referer' => config('app.url')]]` as second parameter of `placeAutocomplete()` could only work with a POST as our array is top level merged with the `$options` variable. But when it's a GET, it's merged in the array key `$options['query'] `. So it's passed like this to Guzzle, and so not work (not recognized as the header parameter). 

Is there any solution to pass custom headers to the request? 

Thanks.

**Comment by Seaclick** [comment]
Hello, we've got exactly the same question.

Thanks.

**Comment by SachinAgarwal1337** [comment]
@mtx-z @Seaclick Currently I am busy. There is a solution to it. I will implement it later. But If you have a solution please feel free open a PR at Develop Branch

**Comment by SachinAgarwal1337** [comment]
@mtx-z @Seaclick Added support for Custom Headers. Check [V 1.4.0](https://github.com/SachinAgarwal1337/google-places-api/releases/tag/1.4.0)

**Comment by mtx-z** [comment]
@SachinAgarwal1337 really cool! Will test asap and report here. Thanks again.

**Comment by SachinAgarwal1337** [comment]
@mtx-z Already Added default header support in this version it self. Please check out the docs.

**Comment by mtx-z** [comment]
Hello @SachinAgarwal1337 ,
I just tested the latest version: everything works. 

Note: in documentation for Laravel, you could specify that the header config key must be under the "places" key (`config('google.places.headers')`). 

Thanks again for the quick support.
