### ISSUE TITLE
Response returned with status: OVER_QUERY_LIMIT

### ISSUE THREAD

**Issue by xyluz** [SachinAgarwal1337/google-places-api#50]
I am trying to make it possible for my application to fetch information about a business from Google. This means the business owner who has an account on my application can decide to populate the fields in my application by using Google but I keep running into this issue: 

message: "Response returned with status: OVER_QUERY_LIMIT↵1",…

How do I fix it?

**Comment by SachinAgarwal1337** [comment]
@xyluz From the Google Docs:
```
OVER_QUERY_LIMIT indicates any of the following:
You have exceeded the QPS limits.
Billing has not been enabled on your account.
The monthly $200 credit, or a self-imposed usage cap, has been exceeded.
The provided method of payment is no longer valid (for example, a credit card has expired).
See the Maps FAQ for more information about how to resolve this error.
```

ref: https://developers.google.com/places/web-service/details#ErrorMessages
