### ISSUE TITLE
 Does this work with Laravel 6.x?

### ISSUE THREAD

**Issue by MiqueiasMaia** [SachinAgarwal1337/google-places-api#53]
Dears,

I'm doing an app that needs Google Places API. I'm using Laravel 6.x. Does this work good with this version? I haven't saw any question or taking about the interation for this package with Laravel 6.x until this moment.

**Comment by MiqueiasMaia** [comment]
I'm needing this informations:

- Place ID
- Latitude
- Longitude
- Address (street, number, city, state, country)
- Place photos

**Comment by SachinAgarwal1337** [comment]
@MiqueiasMaia It is compatible with Laravel 6.x. You can give it a try.

**Comment by MiqueiasMaia** [comment]
> @MiqueiasMaia It is compatible with Laravel 6.x. You can give it a try.

Thnx for u response.
I will try.
