### ISSUE TITLE
Radar search issues

### ISSUE THREAD

**Issue by DMNSteve** [SachinAgarwal1337/google-places-api#6]
Noticed a couple of typos and issues with the handling of radar search parameters

**Comment by SachinAgarwal1337** [comment]
@DMNSteve Can you please give more info about the issue? Like where exactly is the typo and what exactly is the issue with radar search parameters? 
It will be help in fixing it faster.

**Comment by DMNSteve** [comment]
Ive raised a PR for you to look at :)

**Comment by SachinAgarwal1337** [comment]
Fixed it.

**Comment by DMNSteve** [comment]
Thank you!
