### ISSUE TITLE
Support for retrieving place ratings, opening hours and reviews?

### ISSUE THREAD

**Issue by blessingdube** [SachinAgarwal1337/google-places-api#60]
Hi,

Thanks for the package, it's awesome!

One thing I haven't been able to work out is whether there is support for retrieving additional fields like ratings, opening hours and reviews for places?

If it does then I apologise for creating this issue.

If someone can confirm that this feature is absent then I can have a look into how viable it would be to add it against the Google documentation and can look at contributing to the package if others will find it useful.

Thanks,
Blessing

**Comment by SachinAgarwal1337** [comment]
@blessingdube you should be able to get that info from `Place Details API`

**Comment by SachinAgarwal1337** [comment]
@blessingdube Thank you :)
And yes, you should be able to get that info from `Place Details API`

**Comment by blessingdube** [comment]
@SachinAgarwal1337 thanks for your response. How is the API expecting the "fields" to be passed in so the Google Places API knows to returning the "opening_times" part of the response?

**Comment by SachinAgarwal1337** [comment]
@blessingdube Have a look at this: https://github.com/SachinAgarwal1337/google-places-api#place-details
Second Parameter is a plain array in which you can pass any params to the API
