### ISSUE TITLE
API KEY is not specified

### ISSUE THREAD

**Issue by KautsarH** [SachinAgarwal1337/google-places-api#66]
Hi, I have problems with this. Eventhough I already set the API key, it doesn't seem to work. I followed the steps for laravel. The API key is legit.
![image](https://user-images.githubusercontent.com/36438908/96300055-8705b800-1027-11eb-99a1-01d67407e071.png)

![image](https://user-images.githubusercontent.com/36438908/96299931-5aea3700-1027-11eb-97a9-e8a66e0303fb.png)
[](url)

**Comment by SachinAgarwal1337** [comment]
@KautsarH  you need to set the API Key in .env file and not in the google.php like that.

```
.env

GOOGLE_PLACES_API_KEY=yourApiKeyHere
```

```
google.php

return [
    'places' => [
        'key' => env('GOOGLE_PLACES_API_KEY', null),
        ...
    ]
]
```

**Comment by KautsarH** [comment]
Thank you! I got confused 😁
