### ISSUE TITLE
PHP 5.6 support issue

### ISSUE THREAD

**Issue by maxguru** [SachinAgarwal1337/google-places-api#67]
According to composer.json, PHP 5.6 is supported, however, I'm getting a syntax error.
```
Parse error:  syntax error, unexpected '?' in ..../vendor/skagarwal/google-places-api/src/PlacesApi.php on line 258
```
The code is using the null coalescing operator which was added in PHP 7.0.

**Comment by SachinAgarwal1337** [comment]
removed support for php 5.6
