### ISSUE TITLE
Add Support for PHP 8

### ISSUE THREAD

**Issue by IlliaBalia** [SachinAgarwal1337/google-places-api#70]
Please, consider updating `composer.json` file to 
```
"require": {
        "php": "^5.5.9|^7.2|^7.3|^8.0",
        ...
}
```
in order to support PHP 8

**Comment by daniser** [comment]
Also, there's no sense in ^7.3 constraint here. 7.3 and 7.4 already covered by ^7.2 constraint.

**Comment by aitor72** [comment]
Please update this @daniser

**Comment by SachinAgarwal1337** [comment]
Done in https://github.com/SachinAgarwal1337/google-places-api/pull/71
