### ISSUE TITLE
lat and long in autocomplete

### ISSUE THREAD

**Issue by arthimann** [SachinAgarwal1337/google-places-api#72]
Hi,

When I'm trying to get only cities and countries:
```php
[
                'types' => '(cities)',
]
```

For some reason, I can't get city lat and long. In the JS version lat and long are exists. Then how I can get those details in the response?

**Comment by SachinAgarwal1337** [comment]
@arthimann The package retruns the entire response received from the google APIs. Please check the google docs once for possible responses.
