### ISSUE TITLE
Nearby Search doesn't return all fields documented in official Google documentation

### ISSUE THREAD

**Issue by joldnl** [SachinAgarwal1337/google-places-api#73]
The `nearbySearch` method returns results, and I am able to retrieve them fine, but I wanted to use the address fields of the place documented in the [Google Places API documentation for nearby search results](https://developers.google.com/maps/documentation/places/web-service/search-nearby#Place).

But, among others `address_components`, `adr_address`, `formatted_address`.  are missing in the results.

The only fields returned are:
- business_status
- geometry
- icon
- icon_background_color
- icon_mask_base_uri
- name
- opening_hours
- place_id
- plus_code
- rating
- reference
- scope
- types
- user_ratings_total
- vicinity

I am doing the following:

```php
$googlePlaces = new PlacesApi($this->api_key);

$params = [
    'keyword' => 'restaurant',
    'name' => null,
    'types' => null,
    'pagetoken' => $next_page_token
];

$response = $googlePlaces->nearbySearch($this->location, $this->radius, $params);
$results = $response->all()['results']->all();
var_dump($response);

```

Am I missing something? How can I get the address details of a place in the results of the nearby search? Of course I can do another api call and get those data but we're doing a large amount of queries so that would double our api usage.

**Comment by SachinAgarwal1337** [comment]
@joldnl if you check the same google documentation you mentioned, you will find the following.
<img width="907" alt="Screenshot 2022-03-23 at 01 13 44" src="https://user-images.githubusercontent.com/5370915/159563012-49b5860e-4fd4-4b67-86f8-1470f9466fc7.png">
<img width="857" alt="Screenshot 2022-03-23 at 01 13 51" src="https://user-images.githubusercontent.com/5370915/159563043-3ce4c2ac-f3c4-44f2-af31-ef6880426478.png">


Hope this helps
