### ISSUE TITLE
Facade access in Laravel 10

### ISSUE THREAD

**Issue by citricguy** [SachinAgarwal1337/google-places-api#75]
I cannot seem to get the facade working in Laravel 10, or at least code completion in PHPStorm.

I get this error: 
Class "App\Http\Livewire\Company\GooglePlaces" not found

When running:
$this->apiStuff = GooglePlaces::placeAutocomplete('some city');

I can get `GooglePlaces::placeAutocomplete('some city');` to work from other parts of my app (ie., web.php), but code completion doesn't seem to work.

The documented, non-laravel works as documented.
```
use SKAgarwal\GoogleApi\PlacesApi;

function () {
  $googlePlaces = new PlacesApi('API_KEY') # line 1
  $response = $googlePlaces->placeAutocomplete('some input'); # line 2
}
```

**Comment by citricguy** [comment]
This might only be a [DocBlock](https://laravel-news.com/automatic-docblock-generation-on-facades) issue.

I can get the actual facade working working if I add `use GooglePlaces;` to my class, and I can get Auto-completion working if I install and use `sail artisan ide-helper:generate` from the https://github.com/barryvdh/laravel-ide-helper package.

**Comment by SachinAgarwal1337** [comment]
@citricguy You will have to add the use statement of the facade for it to be working. Just like any other facade in Laravel.
