### ISSUE TITLE
New Google Places API URL and method migration

### ISSUE THREAD

**Issue by ghost** [SachinAgarwal1337/google-places-api#76]
Are there plan to update the BASE_URL from `public const BASE_URL = 'https://maps.googleapis.com/maps/api/place/';` to the new Google Places API base URL: `https://places.googleapis.com/v1/places:searchText` ([Migrate to Text Search (New)](https://developers.google.com/maps/documentation/places/web-service/migrate-text))?

**Comment by SachinAgarwal1337** [comment]
@lorenzo-rditaly Definitely. Might take sometime based on my schedule. But Definitely will be updating it.

**Comment by SachinAgarwal1337** [comment]
This is now released in https://github.com/SachinAgarwal1337/google-places-api/releases/tag/3.0.0
