### ISSUE TITLE
array_and_keys_exists issue

### ISSUE THREAD

**Issue by jacber** [SachinAgarwal1337/google-places-api#8]
Hey,

This doesn't seem to work : 

 function array_any_keys_exists(array $keys, array $array)
    {
        $result = false;
        foreach ($keys as $key) {
            $result = $result OR array_key_exists($key, $array);
        }
        return $result;
    }

changing this line : $result = $result OR array_key_exists($key, $array);
to
if (array_key_exists($key, $array)) return true;
solves the issue .

**Comment by SachinAgarwal1337** [comment]
@jacber fixed it. Thank you for bringing it in notice.
