### ISSUE TITLE
Radar and Nearby Search params problem

### ISSUE THREAD

**Issue by kamililyas** [SachinAgarwal1337/google-places-api#9]
Hello,

Thank you for this laravel library, it helped me a lot. But there is an issue which i wanted to point out that i was facing, in the radar search i was sending one param of the three ('keyword', 'name', 'type') which is the requirement from google, but i always got an exception, saying "Radar Search require one or more of 'keyword', 'name', or 'types' params.". The case was when i provide all three params only then the call was successful, so I dug in a little into your code and found out that the method you have 'array_any_keys_exists' has a condition that will only be true if all keys passed are present in the params array, so i changed the code for it with something like:

```
    function array_any_keys_exists(array $keys, array $array)
    {
        $result = false;

        foreach ($keys as $key) {
            if(array_key_exists($key, $array)){$result = true;break;}
            else{$result = false;}
        }

        return $result;
    }
```

After this change the radar search call executed with any one required param that is passed, same goes for the case of nearby search, your method search for all these three keys, when in fact only one passed should work also. Please let me know your thoughts on this and do correct me if I'm wrong, thank you for your time.

Regards,
Kamil

**Comment by SachinAgarwal1337** [comment]
Hello @kamililyas,

Thank you for sharing this. Can you please tel me which version you are using?

**Comment by kamililyas** [comment]
Pleasure, I think I'm using version 1.0, from my composer.json i can see that.

**Comment by SachinAgarwal1337** [comment]
@kamililyas please update your version to 1.0.4. I have already fixed it in this new version.

**Comment by kamililyas** [comment]
Yes thank you, i already noted that from previous issues, sorry i hadn't looked into them, thanks again.
